export const COLORS = {
  bg: "#0a0f1e",
  card: "#111827",
  border: "#1e293b",
  text: "#f8fafc",
  textLight: "#e2e8f0",
  textMuted: "#94a3b8",
  textDim: "#64748b",
  textDark: "#475569",
  textDarkest: "#334155",
  accent: "#3b82f6",
  accentHover: "#2563eb",
  accentBg: "#1e3a5f",
  accentLight: "#60a5fa",
  success: "#22c55e",
  successHover: "#16a34a",
  warning: "#f59e0b",
  danger: "#ef4444",
  purple: "#5b21b6",
};

export const commonStyles = {
  page: {
    minHeight: "100vh",
    width: "100%",
    background: COLORS.bg,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    fontFamily: "'Georgia', serif",
    padding: "0 16px 40px",
    boxSizing: "border-box",
  },
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    maxWidth: 480,
    width: "100%",
    padding: "20px 0",
  },
  title: {
    fontSize: 36,
    fontWeight: "bold",
    color: COLORS.text,
    margin: "0 0 8px",
    letterSpacing: "-1px",
  },
  subtitle: {
    color: COLORS.textDim,
    fontSize: 15,
    marginBottom: 16,
  },
  backBtn: {
    background: "transparent",
    border: "none",
    color: COLORS.textDark,
    cursor: "pointer",
    fontSize: 14,
    fontFamily: "sans-serif",
    padding: "4px 0",
  },
  logoutBtn: {
    position: "absolute",
    top: 20,
    right: 20,
    background: "transparent",
    border: `1px solid ${COLORS.border}`,
    borderRadius: 8,
    color: COLORS.textDim,
    fontSize: 13,
    fontFamily: "sans-serif",
    cursor: "pointer",
    padding: "6px 14px",
  },
  input: {
    width: "100%",
    padding: "14px 16px",
    background: COLORS.card,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 12,
    color: COLORS.text,
    fontSize: 15,
    fontFamily: "sans-serif",
    boxSizing: "border-box",
    outline: "none",
  },
  primaryBtn: {
    width: "100%",
    background: COLORS.accent,
    color: "white",
    border: "none",
    borderRadius: 12,
    padding: "14px",
    fontSize: 15,
    fontWeight: "600",
    cursor: "pointer",
    fontFamily: "sans-serif",
  },
  cardBox: {
    background: COLORS.card,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 14,
    padding: "18px 20px",
    width: "100%",
    boxSizing: "border-box",
  },
  progressBarTrack: {
    width: "100%",
    height: 4,
    background: COLORS.border,
    borderRadius: 4,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    background: COLORS.success,
    borderRadius: 4,
    transition: "width 0.4s ease",
  },
  spinner: {
    width: 40,
    height: 40,
    border: `3px solid ${COLORS.border}`,
    borderTop: `3px solid ${COLORS.accent}`,
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
};
