export const FONT = "'Inter', 'Open Sans', Helvetica, Arial, sans-serif";

export const COLORS = {
  bg: "#fcf9ee",
  bgGradient: "linear-gradient(#fff, #fcf9ee 30%, #fcf9ee)",
  card: "#ffffff",
  cardAlt: "#faf7f0",
  border: "#e8e0d4",
  borderLight: "#f0ebe3",
  text: "#3d3332",
  textLight: "#5c4a49",
  textMuted: "#7c6a69",
  textDim: "#9c8a89",
  textDark: "#b0a09f",
  textDarkest: "#c8bfbe",
  accent: "#b45309",
  accentHover: "#92400e",
  accentBg: "#fef3c7",
  accentLight: "#d97706",
  success: "#16a34a",
  successHover: "#15803d",
  warning: "#d97706",
  danger: "#dc2626",
  purple: "#7c3aed",
};

export const commonStyles = {
  page: {
    minHeight: "100vh",
    width: "100%",
    background: COLORS.bgGradient,
    backgroundColor: COLORS.bg,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    fontFamily: FONT,
    padding: "0 16px 40px",
    boxSizing: "border-box",
    color: COLORS.text,
  },
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    maxWidth: 480,
    width: "100%",
    padding: "20px 0",
  },
  title: {
    fontSize: 32,
    fontWeight: "600",
    color: COLORS.text,
    margin: "0 0 8px",
    letterSpacing: "-0.5px",
  },
  subtitle: {
    color: COLORS.textMuted,
    fontSize: 15,
    marginBottom: 16,
  },
  backBtn: {
    background: "transparent",
    border: "none",
    color: COLORS.textDim,
    cursor: "pointer",
    fontSize: 14,
    fontFamily: FONT,
    padding: "4px 0",
    fontWeight: "500",
  },
  logoutBtn: {
    position: "absolute",
    top: 20,
    right: 20,
    background: "transparent",
    border: `1px solid ${COLORS.border}`,
    borderRadius: 8,
    color: COLORS.textDim,
    fontSize: 13,
    fontFamily: FONT,
    cursor: "pointer",
    padding: "6px 14px",
  },
  input: {
    width: "100%",
    padding: "14px 16px",
    background: COLORS.card,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 12,
    color: COLORS.text,
    fontSize: 15,
    fontFamily: FONT,
    boxSizing: "border-box",
    outline: "none",
  },
  primaryBtn: {
    width: "100%",
    background: COLORS.accent,
    color: "white",
    border: "none",
    borderRadius: 12,
    padding: "14px",
    fontSize: 15,
    fontWeight: "600",
    cursor: "pointer",
    fontFamily: FONT,
  },
  cardBox: {
    background: COLORS.card,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 14,
    padding: "18px 20px",
    width: "100%",
    boxSizing: "border-box",
  },
  progressBarTrack: {
    width: "100%",
    height: 4,
    background: COLORS.borderLight,
    borderRadius: 4,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    background: COLORS.success,
    borderRadius: 4,
    transition: "width 0.4s ease",
  },
  spinner: {
    width: 40,
    height: 40,
    border: `3px solid ${COLORS.border}`,
    borderTop: `3px solid ${COLORS.accent}`,
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
};
